name: NuGet Push Public

on: [workflow_dispatch]

jobs:
  build-test-prep-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: |
            3.1.x
            5.0.x
            6.0.x

        env:
          DOTNET_INSTALL_DIR: /usr/share/dotnet
      - name: Create the package
        run: dotnet test ./src/CSharp/EasyMicroservices.Serialization.sln && dotnet pack ./src/CSharp/EasyMicroservices.Serialization.sln -c Release --output nupkgs
      - name: Publish the package to NuGet.org
        env:
          NUGET_KEY: ${{secrets.NUGET_KEY}}
        run: dotnet nuget push nupkgs/*.nupkg -k $NUGET_KEY -s https://api.nuget.org/v3/index.json
